baseURL = 'https://github.com/yukimatsuda1999/notemy/blob/main/themes/hugo-theme-notemy/static/'
languageCode = 'ja-jp'
title = 'Notemy  --Personal Website'

theme = 'hugo-theme-notemy'

copyright = "(É”) 2022 Yuki Mastuda"


[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

	[markup.highlight]
		noClasses=false
