baseURL = 'https://notemy.netlify.app/'
languageCode = 'ja-jp'
title = 'Notemy - Personal Website for Memorandum'

theme = 'hugo-theme-notemy'

copyright = "(É”) 2022 Yuki Mastuda"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

	[markup.highlight]
		noClasses=false
